name: games_richpresence
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.0
  flutter_svg: ^2.0.10+1
  easy_localization: ^3.0.5
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.3.0
  dart_discord_rpc:
    git:
      url: https://github.com/AlexisL61/dart_discord_rpc.git
  http: ^1.2.0

dev_dependencies:
  build_runner:
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  image_path: "assets/common/png/app-icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  linux: true
  web:
    generate: true
    image_path: "assets/common/png/app-icon.png"
  windows:
    generate: true
    image_path: "assets/common/png/app-icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/common/png/app-icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/common/icons/
    - assets/sea_of_thieves/svg/buttons/
    - assets/sea_of_thieves/svg/panels/
    - assets/sea_of_thieves/svg/background/
    - assets/sea_of_thieves/png/
    - assets/sea_of_thieves/icons/
    - assets/sea_of_thieves/separator/
    - assets/translations/

  fonts:
    - family: Windlass
      fonts:
        - asset: assets/sea_of_thieves/fonts/windlass.ttf
