name: Pre-release App
  # You may pin to the exact commit or the version.
  # uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
    
on:
  push:
     branches: [ dev ]
     
jobs:
 retrievingVersion:
  runs-on: ubuntu-latest
  outputs:
      version: ${{ steps.versionstep.outputs.version }}
      previousTag: ${{ steps.previousTag.outputs.previousTag }}
  steps:
    - uses: actions/checkout@v3
      with: 
        fetch-tags: true
        fetch-depth: 0
    - name: Expose git commit data
      uses: rlespinasse/git-commit-data-action@v1
    - name: Retrieve Release Version
      id: versionstep
      working-directory: rpc_express
      run: |
         VERSION=$(more pubspec.yaml | grep version: | cut -d ' ' -f2)
         echo "version=${VERSION}-beta" >> $GITHUB_OUTPUT
         echo "VERSION=${VERSION}-beta" >> $GITHUB_ENV
 build_windows:
   runs-on: windows-latest
   needs: retrievingVersion
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
        flutter-version: '3.24.3'
        channel: 'stable'
     - name: Build windows
       working-directory: ./rpc_express
       run: flutter build windows -t ./lib/main_entrypoint.dart --build-name ${{ needs.retrievingVersion.outputs.version }}
     - uses: actions/upload-artifact@v3
       with:
          name: build_windows
          path: ./rpc_express/build/windows/x64/runner/Release
 build_linux:
   runs-on: ubuntu-latest
   needs: retrievingVersion
   steps:
     - uses: actions/checkout@v3
     - run: |
        sudo apt-get update -y
        sudo apt install libmpv-dev mpv
        sudo apt-get install -y ninja-build libgtk-3-dev
     - uses: subosito/flutter-action@v2
       with:
        flutter-version: '3.24.3'
        channel: 'stable'
     - name: Build linux
       working-directory: ./rpc_express
       run: flutter build linux -t ./lib/main_entrypoint.dart --build-name ${{ needs.retrievingVersion.outputs.version }}
     - uses: actions/upload-artifact@v3
       with:
          name: build_linux
          path: ./rpc_express/build/linux/x64/release/bundle
 upload:
    runs-on: ubuntu-latest
    needs: 
      - build_windows
      - build_linux
      - retrievingVersion
    steps: 
      - uses: actions/checkout@v3
        with:
          ref: dev
      - run: mkdir -p dist
      - uses: actions/download-artifact@v3
        with:
          name: build_windows
          path: dist/RPC_Express_Windows
      - uses: actions/download-artifact@v3
        with:
          name: build_linux
          path: dist/RPC_Express_Linux
      - name: Zipping windows release
        working-directory: dist/RPC_Express_Windows
        run: |
          zip -r ../../RPC_Express_Windows.zip *
      - name: Zipping linux release
        working-directory: dist/RPC_Express_Linux
        run: |
          zip -r ../../RPC_Express_Linux.zip *
      - name: Upload release onto Github
        uses: ncipollo/release-action@v1
        with:
         artifacts: 'RPC_Express_Windows.zip,RPC_Express_Linux.zip'
         token: ${{ secrets.GITHUB_TOKEN }}
         tag: ${{ needs.retrievingVersion.outputs.version }}
         prerelease: true
         allowUpdates: true
  